### ISSUE TITLE
Add bounds check for length of passed indices and values

### ISSUE THREAD

**Issue by tlnagy** [JuliaArrays/IndirectArrays.jl#18]
~~This seems like a pretty massive bug unless I'm totally reading this wrong~~ I was reading this wrong, but this check should still occur.

```julia
julia> c = IndirectArray([1,1,1,2,2,2], ["A", "A", "A", "B", "B", "B"])
6-element IndirectArray{String,1,Array{Int64,1},Array{String,1}}:
 "A"
 "A"
 "A"
 "A"
 "A"
 "A"

julia> versioninfo()
Julia Version 1.0.0
Commit 5d4eaca0c9 (2018-08-08 20:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 2700X Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, znver1)
```

IndirectArrays v0.5.0

**Comment by tlnagy** [comment]
```julia
julia> dump(c)
IndirectArray{String,1,Array{Int64,1},Array{String,1}}
  index: Array{Int64}((6,)) [1, 1, 1, 2, 2, 2]
  values: Array{String}((6,))
    1: String "A"
    2: String "A"
    3: String "A"
    4: String "B"
    5: String "B"
    6: String "B"
```

So it looks like it is working, but it needs a bounds check or something because it requires that `unique(index) == length(values)` but this isn't enforced.

**Comment by nalimilan** [comment]
Strictly speaking what it required is `unique(index) ⊆ 1:length(values)`. And AFAICT that's enforced:
```julia
julia> IndirectArray([1,10], ["a"]);
ERROR: BoundsError: attempt to access 1-element Array{String,1} at index [[1, 10]]
```
Providing some duplicated and some unused levels as in your example isn't very useful, but I'm not sure it should be forbidden.

**Comment by timholy** [comment]
Right, a good example is let's say you want to provide a gray color scale for an indexed image, but color saturated pixels red. I might get a constant stream of images from my camera, some of which might have saturated pixels and others not; I don't want to have to change my color map dependent on whether pixels actually "hit" each value or not.

**Comment by tlnagy** [comment]
@timholy your explanation makes a lot of sense. I was suspecting that something like that was the reasoning. Thanks!
